### ISSUE TITLE
support for HAPROXY TCP PROXY v1 protocol

### ISSUE THREAD

**Issue by hudecof** [jedisct1/pure-ftpd#111]
Hi,

is there a plan to support HAPROXT TCP PROXY v1 protocol ? See https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

In some cases just the `--forcepassiveip` is good enough, but in my scenario there are several HAPROXY servers in active/active mode.

It should not be very hard to implement.

**Comment by jedisct1** [comment]
There are absolutely no plans to implement this unless this is contracted work.

**Comment by hudecof** [comment]
@jedisct1 I have got code for this, but need some code review to fit your standart. Also docs are still missing. Could I create WIP MR ?

**Comment by jedisct1** [comment]
Maybe keeping this as a fork or as patches would be best.

This is a very specific feature, for a specific product, that no one ever asked for before, and the changes directly affect sockets used for everything else.

It's also complicated to test, as it requires a specific environment, with a specific configuration that I even don't have any idea how to build.

This is something I will probably never have the time test, that I don't know how to support and that is likely to completely break after a small unrelated change.

It is better kept as a separate project or fork, that you, as an expert in this, can keep improving so that 
it's as good as possible.

If it ends up in the main pure-ftpd code, the code is bound to rot; it won't get any maintenance even for security issues.
