### ISSUE TITLE
Can clearargs be flaggable

### ISSUE THREAD

**Issue by lyda** [jedisct1/pure-ftpd#22]
It would be nice to see the current pure-ftp config. The `clearargs()` function in ftpd.c kind of ruins that. I get that there are Sound Security Reasons[0] for not doing so, but for those of us willing to take the risk it would be a nice option if we're trying to confirm the current configuration of pure-ftpd.

I can send a pull-request with the change, but just seeing if you'd be open to it and if you had a preferred option letter.

[0] There aren't really, but I know some think there are.

**Comment by jedisct1** [comment]
Hi Lyda,

The main reason for `clearargs()` is that Linux still doesn't provide `setproctitle(3)`.

As a result, overwriting the command-line arguments buffer is required in order to change the process name.

Knowing which process does what by looking at its name is quite useful, and changing this behavior now is probably a bad idea. There are probably even people running scripts depending on these.

An alternative way to start the service is by using a configuration file. While it doesn't confirm that the running service matches the current configuration, it's still a pretty good hint for it :)
