### ISSUE TITLE
Hostname defined for forcepassiveip always resolves to an IP on the LAN

### ISSUE THREAD

**Issue by perryao** [jedisct1/pure-ftpd#53]
I'm attempting to specify the domain name to respond to clients (something like `ftp.example.com`). Problem I'm having is that by the time pureftpd responds to PASV requests, it resolves `ftp.example.com` to an IP address on the LAN like 10.x.x.x. Is there  a way to prevent this behavior and instead inform clients to send PASV requests to the public ip of ftp.example.com?

**Comment by jedisct1** [comment]
Hi!

It resolves the name to the IP as the server operating system would. So if you get a `10.x.y.z` address, this is what it resolves to. Maybe this IP comes from your router that acts as a DNS server.

For the `ForcePassiveIP` property, you can specify an IP address directly. So, just put the external IP address here.
If the external IP address is constantly changing, because it's a residential dynamic IP address, use a service such as https://noip.com that will register and update a name mapping to your current IP. Then you can use that name in `ForcePassiveIP`.

**Comment by perryao** [comment]
Thanks for the advice. We have a domain that we're pointing to an AWS load balancer, so the IP isn't quite static. Based on your suggestion, I ended up querying google DNS to find the external IP of the domain before launching pure-ftpd. Thanks again!
