### ISSUE TITLE
virtualuser line max length is 2048

### ISSUE THREAD

**Issue by jacky15** [jedisct1/pure-ftpd#59]
HI all:
We want to set many "allow client ip" (around 100+)  for each virtualuser. 
However,  we got "invalid line" warning from **pure-pw** since the line is longer than 2048 char.

I found there is "LINE_MAX" settings in the source code.Can I make this larger?
May cause any security problem?

by the way, please forgive my poor English.

**Comment by jedisct1** [comment]
That's a lot of IPs :) Don't forget that subnets (`1.2.3.0/24`) are also allowed, so maybe this can be useful to reduce the number of IPs.

That said, you can safely increase `LINE_MAX` if you really need to.

**Comment by jacky15** [comment]
thank you for your reply.However, after I make the "LINE_MAX" to 40960, it still shows the warning.
I change the value in file pure-pw.h line 33.Did I miss something?

**Comment by jedisct1** [comment]
Make sure that the line is actually correct, beyond its size.

There are two `LINE_MAX` definitions (and the default is `4096` not `2048`), but you can override them the same way, at configuration time:

```
env CPPFLAGS=-DLINE_MAX=40960 ./configure --with-everything ...
```

Don't forget a `make clean` after that in order to wipe out possible leftovers from a previous compilation.

**Comment by jacky15** [comment]
IT WORKS!

thanks a lot~
