### ISSUE TITLE
Feature request: SNI support

### ISSUE THREAD

**Issue by aletson** [jedisct1/pure-ftpd#72]
It would be nice to have support for SNI implemented in Pure-FTP for environments where the server can be connected to with multiple domain names to avoid certificate mismatches. Right now, I'm just using a certificate for my primary domain, but would prefer to just have that as a default and be able to use other certificates for other domains, or reject connections from unrecognized hostnames. Is this something that could be implemented in pure-ftpd?

**Comment by banar** [comment]
Yes, it would be nice to see the SNI support.

**Comment by jedisct1** [comment]
+1

**Comment by tandyuk** [comment]
+1
We also use cpanel, and I would prefer to continue using Pure-ftpd, however this feature is beginning to get critical as the lack of SNI can cause PCI compliance issues do to an invalid/self signed cert, when the domain being tested has its own, often wildcard, certificate which is in use by every other service tested.

**Comment by dannetstudio** [comment]
+1

**Comment by FGasper** [comment]
If I may: an ideal way to have SNI support in PureFTPd would be a dynamic specification of key/certificate file per SNI lookup. For example, Exim’s configuration file format allows a dynamic configuration, not just of a static correlation between the SNI string and key/certificate file. Dovecot, as a counterexample, requires servers that host thousands of domains to have ever-growing configuration files because every single domain requires a separate configuration file entry.

Compare exim.conf and dovecot/sni.conf on a cPanel box for good examples of what I mean.

**Comment by Shigbeard** [comment]
+1, it bothers me that I keep getting invalid hostname errors whenever I connect, and I'd rather not sacrifice the other benefits of Pure-FTPD and switch to ProFTPD.

**Comment by jedisct1** [comment]
I wrote `+1` and nothing happened either :(

**Comment by TLWebdesign** [comment]
any news on this?

**Comment by jedisct1** [comment]
Nope, nobody wrote the code for it, or if people did, they didn't share anything.

**Comment by jedisct1** [comment]
To be honest, I don't even understand what the feature request is.

What exact options should be added? What would they do? Can you provide actual examples?

**Comment by TLWebdesign** [comment]
Well on a shared server you have exim support SNI so you don't have to rely on the root cert but can use the user domain certificate instead and it'll accept it as a valid certificate. it does this using SNI. Problem with pure-ftpd is that it doesn't have support for SNI. I don't know anything about the internal workings of this tho. I'm just the end user wanting to have valid SSL certificates for my FTP.

**Comment by FGasper** [comment]
The way I envision this feature working is some sort of pluggable mechanism that returns the TLS key & cert chain for a given servername (SNI string). They can even all be in the same text blob; OpenSSL knows what to do with that.

Perhaps something similar to the workflow for custom authn modules, e.g., an `--sni-handler=` option that gives the path of a script that accepts the SNI string as an argument and spits back the key and cert chain in PEM format. Then pure-ftpd accepts that and hands it off to OpenSSL.

**Comment by jedisct1** [comment]
A client connects. At this point, there is no TLS, and the server doesn't have any ways to know what domain name the clients resolved to reach the server.

Server: Hi

Client: What extensions do you support?

Server: Quite a few, including TLS

Client: Let's switch to TLS, then.

Server: Ok

The client sends a few things to start the TLS negociation, including the domain name it originally connected to. Ignoring domain fronting, that's the SNI information.

The servers gets that domain name. What does it do with it?

Does it load a specific certificate to present the server? Where from, according to the name? What happens if there is no matching certificate?

What are the exact configuration options that have to be added to `pure-ftpd.conf`? What do they do?

How does it affect logging?

**Comment by FGasper** [comment]
> The servers gets that domain name. What does it do with it?
Assuming pure-ftpd was invoked with `--sni-handler=/path/to/sni/handler`, it does: `exec('/path/to/sni/handler', $sni_string)`. The result of that execution is given to OpenSSL as the key and certificate chain.

> Does it load a specific certificate to present the server? Where from, according to the name?
The `/path/to/sni/handler` command/script is what determines which certificate to present. Pure-FTPd doesn’t need to worry about it.

> What happens if there is no matching certificate?
If there is no key/cert-chain returned, then give the same certificate (the “default”) configured via the existing options. If an invalid key/cert-chain is returned, then log the error, and serve up the default certificate.

**Comment by jedisct1** [comment]
That wouldn't work. For SNI, all the certificates have to be loaded prior to knowing which one the client is going to use.

**Comment by FGasper** [comment]
How do you figure that? Exim’s SNI support doesn’t pre-old the certificates, and neither does the SNI-capable server my dev team manages.

**Comment by jedisct1** [comment]
https://stackoverflow.com/questions/5113333/how-to-implement-server-name-indication-sni

If you have a dev team (!) they can implement this.

**Comment by FGasper** [comment]
I’ll see if I can take a crack. Our SNI server is written in Perl, but the workflow should be similar.

Re the SO link you pasted, the sni-handler script would run as part of the callback that `SSL_CTX_set_tlsext_servername_callback()` invokes. The callback creates a new SSL_CTX based on the script results.

**Comment by jedisct1** [comment]
Actually, the post is slightly confusing. Looks like it's possible create a new server context in the SNI callback: https://stackoverflow.com/questions/22373332/serving-multiple-domains-in-one-box-with-sni

Go for it :)

**Comment by FGasper** [comment]
@jedisct1 So, my C is pretty rusty, but here is a first stab:
https://github.com/FGasper/pure-ftpd/tree/sni

What do you think of this approach?

**Comment by jedisct1** [comment]
Done.

Thanks for clarifying what the request was, and how it would work!

That was 99% of what has to be done in order to have it implemented.
