### ISSUE TITLE
Exit status is 0 even when failing to start due to address already in use

### ISSUE THREAD

**Issue by nkgm** [jedisct1/pure-ftpd#75]
Using with `--with-nonroot` and a wrapper script to launch short lived anonymous ftp servers as such:
```
FTP_ANON_DIR=/path/to/dir pure-ftpd -AB
```
Sometimes I may forget the server is already running, and there is no easy way of telling if the launch was successful. Shouldn't exit status be non-zero in the above scenario?

**Comment by jedisct1** [comment]
If you use `-B`, the process is immediately detached from your current session. This could happen at a later stage, but I'm not sure about the implications it would have. This may break existing applications rather than fix common use cases.

But your wrapper could avoid `-B`, or check the presence of the PID file before spawning a new instance.

**Comment by nkgm** [comment]
Forgot to mention that the same exit status behavior is observed even when `-B` is omitted (but at least then you can observe the output error message). Also, when built `--with-nonroot`, there didn't seem to be a `/var/run/pure-ftpd.pid`. Would this be correct?

**Comment by jedisct1** [comment]
There is a `-g <pidfile>` option, that should allow you to place the PID file anywhere.

**Comment by nkgm** [comment]
Good to know. I was thinking about augmenting my script's logic with `lsof` to keep track of running instances (and their ports), but thanks for your help.
